Adjust disk size to be 20GB
Adjust disk size since the image size seems to have increased.

Error below:

ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation
[operation-1592074066726-5a7fba1340e61-2ae76814-4800b8ec]: errors:
- code: RESOURCE_ERROR
  location: /deployments/lustre/resources/nodlustre-hsm1
  message:
"{\"ResourceType\":\"compute.v1.instance\",\"ResourceErrorCode\":\"400\"\
    ,\"ResourceErrorMessage\":{\"code\":400,\"errors\":[{\"domain\":\"global\",\"\
    message\":\"Invalid value for field
'resource.disks[0].initializeParams.diskSizeGb':\
    \ '10'. Requested disk size cannot be smaller than the image size
(20 GB)\",\"\
    reason\":\"invalid\"}],\"message\":\"Invalid value for field
'resource.disks[0].initializeParams.diskSizeGb':\
    \ '10'. Requested disk size cannot be smaller than the image size
(20 GB)\",\"\
    statusMessage\":\"Bad